### ISSUE TITLE
False killer whale library

### ISSUE THREAD

**Issue by sfregosi** [sfregosi/llamp-hub#2]
@sfregosi I can't remember if we decided on any details for creating a FKW library of sample sounds/spectrograms.
I'm looking through old data sets now and can pull files and make screenshots.
Do you have a folder you want me to save them in?

**Comment by sfregosi** [comment]
@ybarkley great question! I still think it would be really helpful but in terms of where to keep it...great question. Would you prefer to just put them somewhere on the server or have them on GitHub somewhere? 

We could put them in a folder within the [llamp-hub](https://github.com/sfregosi/llamp-hub) if they are ok to be public and we would want to eventually share them with the world. I added you as a collab on that repo. 

Otherwise, I'm very happy to just have them on the server or on Google Drive, especially just for now.

**Comment by ybarkley** [comment]
I can put it on the server for now. That's easy! There are screenshots and
recordings so far. Good times.

**Comment by ybarkley** [comment]
- [x] Put Pc_Library folder somewhere in another folder where Selene can access it

@sfregosi Pseudorca files are now here and I'll keep updating them as I go through more Pc stuff:
             Picqueenfish\psd2\CRP\Other Acoustic Data Files\Pseudorca

**Comment by sfregosi** [comment]
@ybarkley Thank you for starting and keeping this going! I'm going to move it to done for now, but it is already being used as I shared it's server location with Jenny!
